# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [1]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [2]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [3]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int64


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [4]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [7]:
d = np.matrix([[9,8,7],[6,5,4],[3,2,1]])

In [9]:
d

matrix([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [8]:
d.T

matrix([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [10]:
d + 1

matrix([[10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [14]:
nd6 = np.matrix([[ 1, 4, 9, 121, 144, 169], [ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])

In [15]:
nd6.mean()

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [2]:
import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [4]:
football=[1,2,2]
flist = np.array(football)
flist

array([1, 2, 2])

In [5]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [6]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [8]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]



39

In [9]:
import pandas as pd

score = [10, 15, 20, 25]

pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [11]:
demo_array=np.arange(0,10) 

In [12]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [14]:
demo_array[demo_array <6]

array([0, 1, 2, 3, 4, 5])

In [15]:
np.max(demo_array)

9

In [16]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [17]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [18]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [19]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

In [20]:
pd.concat[s1, s2]

TypeError: 'function' object is not subscriptable

In [21]:
pd.concat(s1, s2)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "Series"

In [22]:
pd.concat([s1+ s2])

0    ac
1    bd
dtype: object

In [23]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object