In [1]:
import numpy as np

In [2]:
s_list = [1,2,3]

In [3]:
np.array(s_list)

array([1, 2, 3])

In [4]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(0,101,11)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [9]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,50,30)

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(4,4)

array([[0.39401992, 0.21983284, 0.4858754 , 0.15140536],
       [0.05706062, 0.36865917, 0.93770127, 0.49674986],
       [0.18425132, 0.84637973, 0.30029779, 0.63733618],
       [0.18558453, 0.29883656, 0.10972021, 0.72846249]])

In [17]:
# randint(start,end,no of values)
np.random.randint(0,21,10)

array([16,  5, 16,  4,  9,  1,  2, 14,  5, 11])

In [20]:
samp_array = np.arange(20)

In [29]:
rand_array = np.random.randint(0,100,20)

In [37]:
r = samp_array.reshape(5,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
rand_array.argmax()

18

In [36]:
r.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])